name: potential
description: Project for Mutual Fund Clients #Techmatha
version: 2.0.6+7

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.1.0
  google_fonts: ^6.2.0
  intl: ^0.19.0
  provider: any
  jwt_decoder: any
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.4.0
  http: ^1.1.0
  syncfusion_flutter_charts: any
  package_info: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/ic_launcher.png"
  ios: true
  remove_alpha_ios: true


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/


  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true